Declare dependencies with minimum rather than single versions
While pip doesn't have fully-resolved dependency calculations¹, conda
does and correctly detects a version incompatibility between these two
exact versions:

    UnsatisfiableError: The following specifications were found to be in conflict:
      - biopython==1.69 -> numpy=1.12
      - numpy==1.14.3

This is a roadblock to installing sacra requirements into a conda
environment using `conda install`.  By declaring minimums, we let the
dependency resolver figure out how to get us at least the versions we
need (presumably for bug fixes or features).

¹ https://pip.pypa.io/en/stable/user_guide/#requirements-files
  https://github.com/pypa/pip/issues/988